/****************************************************************************
**
** Copyright (C) 2007~2012 Colin Willcocks.
** Copyright (C) 2005~2007 Uco Mesdag. 
** All rights reserved.
** This file is part of "GT-100 Fx FloorBoard".
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License along
** with this program; if not, write to the Free Software Foundation, Inc.,
** 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
**
****************************************************************************/

#include "stompbox_pdl.h"

stompbox_pdl::stompbox_pdl(QWidget *parent)
    : stompBox(parent)
{
    /* PDL */
    setImage(":/images/pdl.png");
    setLSB("06", "00");
    setComboBox("08", "00", "10");
    setButton("06", "00", "20", QPoint(0, 110), ":/images/pedal.png");
    editDetails()->patchPos(1778, 40, "06", "20");
    setEditPages();
};

void stompbox_pdl::updateSignal()
{
    updateComboBox("08", "00", "10");
    updateButton("06", "00", "20");
    updateSwitch("06", "00", "20");
};

void stompbox_pdl::setEditPages()
{
    editDetails()->page()->newGroupBox("Pedal FX");
    editDetails()->page()->addSwitch(0, 0, 1, 1, "06", "00", "20", "middle", Qt::AlignCenter);  //Pedal FX on/off
    editDetails()->page()->addGroupBox(0, 0, 1, 1);

    editDetails()->page()->newGroupBox("EXP Pedal Func");
    editDetails()->page()->newStackControl(0);
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "10");
    editDetails()->page()->addStackControl();
    editDetails()->page()->addGroupBox(1, 0, 1, 1);

    editDetails()->page()->insertStackField(0, 0, 1, 2, 1);

    editDetails()->page()->newGroupBox("Accel/CTRL Func");
    editDetails()->page()->newStackControl(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "50");
    editDetails()->page()->addStackControl();
    editDetails()->page()->insertStackField(1, 1, 0, 1, 1);
    editDetails()->page()->addGroupBox(0, 2, 2, 1);

    editDetails()->page()->newGroupBox("EXP Sw Func");
    editDetails()->page()->newStackControl(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "60");
    editDetails()->page()->addStackControl();
    editDetails()->page()->insertStackField(2, 1, 0, 1, 1);
    editDetails()->page()->addGroupBox(0, 3, 2, 1);

    editDetails()->page()->newGroupBox("Sub CTRL1 Func");
    editDetails()->page()->newStackControl(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "70");
    editDetails()->page()->addStackControl();
    editDetails()->page()->insertStackField(3, 1, 0, 1, 1);
    editDetails()->page()->addGroupBox(0, 4, 1, 1);

    editDetails()->page()->newGroupBox("Sub CTRL2 Func");
    editDetails()->page()->newStackControl(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "00");
    editDetails()->page()->addStackControl();
    editDetails()->page()->insertStackField(4, 1, 0, 1, 1);
    editDetails()->page()->addGroupBox(0, 5, 1, 1);

    editDetails()->page()->newGroupBox("Sub EXP Func");
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "20");
    editDetails()->page()->addGroupBox(1, 4, 1, 2);


    editDetails()->page()->newStackField(0);
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(0);
    editDetails()->page()->newGroupBox("Foot Volume");
    editDetails()->page()->addComboBox(0, 0, 1, 2, "06", "00", "30");
    editDetails()->page()->addKnob(1, 0, 1, 1, "06", "00", "31");
    editDetails()->page()->addKnob(1, 1, 1, 1, "06", "00", "32");
    editDetails()->page()->addKnob(2, 0, 1, 2, "06", "00", "33");
    editDetails()->page()->addGroupBox(0, 1, 1, 1);
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(0);
    editDetails()->page()->newGroupBox("Pedal Bend");
    editDetails()->page()->addKnob(0, 0, 1, 2, "06", "00", "22");
    editDetails()->page()->addKnob(1, 0, 1, 2, "06", "00", "23");
    editDetails()->page()->addKnob(2, 0, 1, 1, "06", "00", "24");
    editDetails()->page()->addKnob(2, 1, 1, 1, "06", "00", "25");
    editDetails()->page()->addGroupBox(0, 1, 1, 1);
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(0);
    editDetails()->page()->newGroupBox("Wah");
    editDetails()->page()->addComboBox(0, 0, 1, 1, "06", "00", "26");
    editDetails()->page()->addKnob(0, 1, 1, 1, "06", "00", "27");
    editDetails()->page()->addKnob(1, 0, 1, 1, "06", "00", "28");
    editDetails()->page()->addKnob(1, 1, 1, 1, "06", "00", "29");
    editDetails()->page()->addKnob(2, 0, 1, 1, "06", "00", "2A");
    editDetails()->page()->addKnob(2, 1, 1, 1, "06", "00", "2B");
    editDetails()->page()->addGroupBox(0, 1, 1, 1);
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(0);
    editDetails()->page()->newGroupBox("Pedal Bend");
    editDetails()->page()->addKnob(0, 0, 1, 2, "06", "00", "22");
    editDetails()->page()->addKnob(1, 0, 1, 2, "06", "00", "23");
    editDetails()->page()->addKnob(2, 0, 1, 1, "06", "00", "24");
    editDetails()->page()->addKnob(2, 1, 1, 1, "06", "00", "25");
    editDetails()->page()->addGroupBox(0, 1, 1, 1);
    editDetails()->page()->newGroupBox("Foot Volume");
    editDetails()->page()->addComboBox(0, 0, 1, 2, "06", "00", "30");
    editDetails()->page()->addKnob(1, 0, 1, 1, "06", "00", "31");
    editDetails()->page()->addKnob(1, 1, 1, 1, "06", "00", "32");
    editDetails()->page()->addKnob(2, 0, 1, 2, "06", "00", "33");
    editDetails()->page()->addGroupBox(0, 2, 1, 1);
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(0);
    editDetails()->page()->newGroupBox("Wah");
    editDetails()->page()->addComboBox(0, 0, 1, 1, "06", "00", "26");
    editDetails()->page()->addKnob(0, 1, 1, 1, "06", "00", "27");
    editDetails()->page()->addKnob(1, 0, 1, 1, "06", "00", "28");
    editDetails()->page()->addKnob(1, 1, 1, 1, "06", "00", "29");
    editDetails()->page()->addKnob(2, 0, 1, 1, "06", "00", "2A");
    editDetails()->page()->addKnob(2, 1, 1, 1, "06", "00", "2B");
    editDetails()->page()->addGroupBox(0, 1, 1, 1);
    editDetails()->page()->newGroupBox("Foot Volume");
    editDetails()->page()->addComboBox(0, 0, 1, 2, "06", "00", "30");
    editDetails()->page()->addKnob(1, 0, 1, 1, "06", "00", "31");
    editDetails()->page()->addKnob(1, 1, 1, 1, "06", "00", "32");
    editDetails()->page()->addKnob(2, 0, 1, 2, "06", "00", "33");
    editDetails()->page()->addGroupBox(0, 2, 1, 1);
    editDetails()->page()->addStackField();


    editDetails()->page()->newStackField(1); editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(1);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "51");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "52");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "53");
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(2); editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(2);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "61");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "62");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "63");
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(3); editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(3);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "07", "00", "71");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "07", "00", "72");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "07", "00", "73");
    editDetails()->page()->addStackField();

    editDetails()->page()->newStackField(4); editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();
    editDetails()->page()->newStackField(4);
    editDetails()->page()->addComboBox(0, 0, 1, 1, "08", "00", "01");
    editDetails()->page()->addComboBox(1, 0, 1, 1, "08", "00", "02");
    editDetails()->page()->addComboBox(2, 0, 1, 1, "08", "00", "03");
    editDetails()->page()->addStackField();

    editDetails()->addPage();
};
